dist: trusty
sudo: required
before_install:
  - sleep 10
  - sudo apt-get -qq update
  - sudo apt-get install -y --allow-unauthenticated libpthread-stubs0-dev qtbase5-dev qtdeclarative5-dev cmake gcc

before_script:
  - git clone https://github.com/SSIP/ImpactSearcher.git
  - cd ImpactSearcher && cmake src && make imse && sudo make install && cd ..
script:
  - cmake src && make
